import React, {useEffect, useRef, useState} from 'react';
import {Animated, ImageBackground, Pressable, Text, View} from 'react-native';

const places=[['purpose','The Rooftop','where a direction starts','✦'],['scope','The Bridge','where your world gets bigger','↗'],['orientation','The Path','where you notice movement','➜'],['content','The Studio','where ideas take shape','◈'],['tried','The Workshop','where you get to try','✚'],['seen','The Stoops','where someone sees you','◉'],['helped','The Open Door','where support becomes possible','⌂'],['other','The Corner','where the room makes space','✧']];
export default function CityOfPossibility({styles,signals=[]}){
  const active=new Set(signals.map(s=>s.tag));
  const [selected,setSelected]=useState(null);
  const pulse=useRef(new Animated.Value(0)).current;
  const drift=useRef(new Animated.Value(0)).current;
  useEffect(()=>{Animated.loop(Animated.sequence([Animated.timing(pulse,{toValue:1,duration:1400,useNativeDriver:true}),Animated.timing(pulse,{toValue:0,duration:1400,useNativeDriver:true})])).start();Animated.loop(Animated.sequence([Animated.timing(drift,{toValue:1,duration:7000,useNativeDriver:true}),Animated.timing(drift,{toValue:0,duration:7000,useNativeDriver:true})])).start();},[]);
  const glow=pulse.interpolate({inputRange:[0,1],outputRange:[0.82,1]});
  const skyShift=drift.interpolate({inputRange:[0,1],outputRange:[-8,8]});
  return <View style={styles.cityCard}><Text style={styles.cityKicker}>YOUR CITY OF POSSIBILITY</Text><Text style={styles.cityIntro}>Every real moment adds a place to the map.</Text><View style={styles.cityScene}><Animated.Image source={require('../../assets/our-sky-art.png')} style={[styles.cityImage,{transform:[{translateX:skyShift}],opacity:0.96}]} /><View style={styles.cityGlow}/>{places.map(([tag,name,desc,icon],i)=>{const isActive=active.has(tag);return <Pressable key={tag} accessibilityRole="button" onPress={()=>setSelected(tag)} style={[styles.cityPlace,{left:`${8+(i%4)*24}%`,top:`${15+Math.floor(i/4)*43}%`},!isActive&&styles.cityPlaceDim]}><Animated.View style={{transform:[{scale:isActive?glow:1}]}}><Text style={styles.cityIcon}>{isActive?icon:'·'}</Text><Text style={styles.cityName}>{isActive?name:'not open yet'}</Text><Text style={styles.cityDesc}>{isActive?desc:'add a moment to reveal'}</Text></Animated.View></Pressable>})}<Animated.Text style={[styles.cityPulse,{opacity:pulse}]}>✦</Animated.Text></View><Text style={styles.cityFooter}>{selected?places.find(p=>p[0]===selected)?.[2]:(active.size<8?`${8-active.size} places are still waiting for a moment.`:'Your map is glowing today.')}</Text></View>}
