import React,{useEffect,useRef,useState} from 'react';
import {Animated,ImageBackground,Pressable,ScrollView,Text,View} from 'react-native';
import {loadYouthData} from '../lib/supabase';

const pieces=['first light','a path','a window','a doorway','a spark','a step','a bridge','a signal','a key','a seat','a second path','a new color','a crossing','a roof','a garden','a skyline','a horizon','a gathering','a compass','the picture'];
const chapters=[['NOTICE','notice a feeling, idea, or pull'],['MOVE','try, make, explore, or change'],['CONNECT','reach beyond yourself'],['MAKE ROOM','find support, recognition, or belonging']];
const scenes=[require('../../assets/compass-splash.png'),require('../../assets/our-sky-art.png'),require('../../assets/rooftop-garden.png')];

export default function PuzzleBuild({styles,signals=[],mood}){
  const [personalSignals,setPersonalSignals]=useState(signals),[personalMood,setPersonalMood]=useState(mood);
  const scene= scenes[Math.floor(Date.now()/86400000)%scenes.length];
  useEffect(()=>{let mounted=true;const refresh=()=>loadYouthData().then(data=>{if(!mounted)return;const saved=data.signals?.length?data.signals:data.moments;setPersonalSignals(saved?.length?saved:signals);setPersonalMood(data.mood||mood)}).catch(()=>{});refresh();const timer=setInterval(refresh,1800);return()=>{mounted=false;clearInterval(timer)}},[signals,mood]);
  const unlocked=Math.min(20,1+(personalMood?2:0)+Math.min(12,personalSignals.length*2));
  const progress=useRef(new Animated.Value(0)).current;useEffect(()=>{Animated.spring(progress,{toValue:unlocked/20,useNativeDriver:false,bounciness:5}).start()},[unlocked]);
  const chapterIndex=Math.min(3,Math.floor(unlocked/5));
  return <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.puzzleScroll}><View style={styles.puzzlePage}><Text style={styles.back}>← Today</Text><Text style={styles.eyebrow}>YOUR DAILY BUILD</Text><Text style={styles.puzzleTitle}>Something is{`\n`}taking shape.</Text><Text style={styles.puzzleLead}>You don’t have to finish this now. Move through your day and the picture will keep forming.</Text><View style={styles.chapterRow}>{chapters.map(([title,clue],i)=><View key={title} style={[styles.chapter,{opacity:i<=chapterIndex?1:.45}]}><Text style={styles.chapterDot}>{i<chapterIndex?'✓':i===chapterIndex?'✦':'·'}</Text><Text style={styles.chapterTitle}>{title}</Text><Text style={styles.chapterClue}>{i===chapterIndex?clue:i<chapterIndex?'awake':'waiting'}</Text></View>)}</View><ImageBackground source={scene} style={styles.puzzleCanvas} imageStyle={styles.puzzleImage}>{pieces.map((name,i)=>{const open=i<unlocked;const angle=[-7,4,9,-4,6][i%5];return <Pressable key={name} style={[styles.puzzlePiece,{left:`${4+(i%5)*19}%`,top:`${3+Math.floor(i/5)*24}%`,transform:[{rotate:`${angle}deg`}]},open?styles.puzzlePieceOpen:styles.puzzlePieceClosed]}><Text style={styles.puzzlePieceMark}>{open?'✦':'·'}</Text>{open&&<Text style={styles.puzzlePieceName}>{name}</Text>}</Pressable>})}</ImageBackground><Text style={styles.puzzleProgressLabel}>{unlocked} of 20 pieces awake</Text><View style={styles.puzzleProgressTrack}><Animated.View style={[styles.puzzleProgressFill,{width:progress.interpolate({inputRange:[0,1],outputRange:['0%','100%']})}]}/></View><Text style={styles.puzzleHint}>{unlocked<20?`Next: ${chapters[chapterIndex][1]}. It will happen when it happens.`:'The whole picture is here for today.'}</Text></View></ScrollView>;
}
