import React, {useEffect, useState} from 'react';
import {SafeAreaView, View, Text, Pressable, TextInput, StyleSheet, ActivityIndicator, Image, ScrollView} from 'react-native';
import {StatusBar} from 'expo-status-bar';
import {ensureYouthSession, saveMoment, saveMood, loadYouthData, loadGroupMoods} from './src/lib/supabase';
import LensActivities from './src/components/LensActivities';
import CompassGarden from './src/components/CompassGarden';
import SkyPreview from './src/components/SkyPreview';
import FullSky from './src/components/FullSky';
import CompassPortrait from './src/components/CompassPortrait';

const notes=['I got to run the sound for the showcase 🎚️','Maya noticed I kept the group calm.','The open laptop room made my idea feel possible 💡'];

export default function App(){
  const [boot,setBoot]=useState(true); const [step,setStep]=useState('welcome'); const [tab,setTab]=useState('Today'); const [name,setName]=useState(''); const [code,setCode]=useState(''); const [text,setText]=useState(''); const [mood,setMoodState]=useState(null); const [notes,setNotes]=useState([]); const [signals,setSignals]=useState([]); const [groupMoods,setGroupMoods]=useState([]); const [toast,setToast]=useState(false);
  const setMood=async(next)=>{setMoodState(next); if(next) await saveMood({x:next.x,y:next.y,programCode:code||'pilot'}).catch(()=>{});};
  useEffect(()=>{const timer=setTimeout(()=>setBoot(false),1200); loadYouthData().then(({mood:storedMood,moments,signals:storedSignals})=>{if(storedMood)setMood(storedMood); if(moments?.length)setNotes(moments); if(storedSignals?.length)setSignals(storedSignals)}).catch(()=>{}); return ()=>clearTimeout(timer)},[]);
  useEffect(()=>{loadGroupMoods(code||"pilot").then(setGroupMoods).catch(()=>{})},[code,notes.length]);
  if(boot)return <SafeAreaView style={s.splash}><StatusBar style="dark"/><Image source={require('./assets/compass-splash.png')} style={s.splashArt}/><Text style={s.splashBrand}>compass</Text><Text style={s.splashTag}>notice what moves you.</Text><ActivityIndicator color="#a35e4d" style={{marginTop:22}}/></SafeAreaView>;
  if(step!=='app') return <AuthFlow step={step} setStep={setStep} name={name} setName={setName} code={code} setCode={setCode} onJoin={async()=>{await ensureYouthSession().catch(()=>{});setStep('app')}}/>;
  const save=async()=>{if(text.trim()){await saveMoment({body:text.trim(),tag:'other',programCode:code||'pilot'}).catch(()=>{});setNotes(prev=>[text.trim(),...prev].slice(0,3));setSignals(prev=>[{body:text.trim(),tag:'other'},...prev]);setText('')} setToast(true);setTab('Today');setTimeout(()=>setToast(false),2200)};
  const pattern=notes.length?'You are collecting moments that matter to you.':'Your pattern will appear as you drop a few moments.';
  return <SafeAreaView style={s.safe}><StatusBar style="dark"/><ScrollView contentContainerStyle={s.scrollContent}><Text style={s.brand}>✦ compass</Text>{tab==='Today'&&<><Text style={s.eyebrow}>TUESDAY · WEEK 4 OF 8</Text><Text style={s.hero}>Where are you{`\n`}<Text style={s.italic}>landing today?</Text></Text><Text style={s.lede}>A quick weather check, then a place for the stuff you want to remember.</Text><Pressable style={s.moodCard} onPress={()=>setTab('Mood')}><Text style={s.moodKicker}>TODAY’S WEATHER</Text><Text style={s.moodTitle}>{mood?'Your dot is on the map ✦':'Place yourself on the map →'}</Text><Text style={s.moodSub}>{mood?'You can move it anytime.':'calm ↔ intense · drained ↔ energized'}</Text></Pressable><Pressable style={s.heroButton} onPress={()=>setTab('Drop one')}><Text style={s.heroButtonText}>✦  Drop a moment</Text></Pressable><Text style={s.section}>YOUR SIGNALS</Text><View style={s.signalRow}><Pressable style={s.signal} onPress={()=>setToast(true)}><Text style={s.signalText}>TRY SOMETHING</Text></Pressable><Pressable style={s.signal} onPress={()=>setToast(true)}><Text style={s.signalText}>FEEL SEEN</Text></Pressable><Pressable style={s.signal} onPress={()=>setToast(true)}><Text style={s.signalText}>FIND A WAY</Text></Pressable></View><CompassGarden styles={s} count={notes.length} signals={signals} mood={mood}/><SkyPreview styles={s} moods={groupMoods}/><LensActivities styles={s} onSave={(body,tag)=>{saveMoment({body,tag,programCode:code||"pilot"});setNotes(prev=>[body,...prev].slice(0,3));setSignals(prev=>[{body,tag},...prev])}}/>{notes.map((n,i)=><View key={n} style={s.card}><Text style={s.dot}>●</Text><Text style={s.cardText}>{n}</Text></View>)}</>}{tab==='Mood'&&<Mood mood={mood} setMood={setMood} onBack={()=>setTab('Today')}/>} {tab==='Drop one'&&<><Pressable onPress={()=>setTab('Today')}><Text style={s.back}>← Today</Text></Pressable><Text style={s.eyebrow}>QUICK DROP · 30 SEC</Text><Text style={s.h2}>Tell the story{`\n`}<Text style={s.italic}>your way.</Text></Text><Text style={s.lede}>What happened today that made you feel proud, curious, included, or stuck?</Text><TextInput multiline value={text} onChangeText={setText} placeholder="Okay, so today…" style={s.input}/><Pressable style={s.heroButton} onPress={save}><Text style={s.heroButtonText}>Keep this moment</Text></Pressable></>}{tab==='Our sky'&&<FullSky styles={s} moods={groupMoods} onBack={()=>setTab('Today')} />}{tab==='My power-up'&&<CompassPortrait styles={s} signals={signals} mood={mood} />}<View style={s.nav}>{['Today','Mood','Drop one','Our sky','My power-up'].map(x=><Pressable key={x} onPress={()=>setTab(x)}><Text style={tab===x?s.activeNav:s.navText}>{x}</Text></Pressable>)}</View>{toast&&<View style={s.toast}><Text style={s.toastText}>Your compass moved ✦</Text></View>}</ScrollView></SafeAreaView>
}

function Mood({mood,setMood,onBack}){const [size,setSize]=useState({w:280,h:280});const place=(e)=>{const pad=16;setMood({x:Math.max(pad,Math.min(size.w-pad,e.nativeEvent.locationX)),y:Math.max(pad,Math.min(size.h-pad,e.nativeEvent.locationY)),w:size.w,h:size.h})};return <><Pressable onPress={onBack}><Text style={s.back}>← Today</Text></Pressable><Text style={s.eyebrow}>WEATHER CHECK · 10 SEC</Text><Text style={s.h2}>Where are you{`\n`}<Text style={s.italic}>landing?</Text></Text><Text style={s.lede}>Tap anywhere. There is no right spot.</Text><View style={s.gridShell}><Text style={s.gridTopLeft}>intense</Text><Text style={s.gridTopRight}>energized</Text><View onLayout={(e)=>{const {width,height}=e.nativeEvent.layout;setSize({w:width,h:height})}} style={s.grid}><Pressable style={s.gridTouch} onPress={place}><View style={s.gridV}/><View style={s.gridH}/>{mood&&<Text style={[s.gridDot,{left:mood.x-15,top:mood.y-15}]}>✦</Text>}</Pressable></View><Text style={s.gridBottomLeft}>calm</Text><Text style={s.gridBottomRight}>drained</Text></View><Text style={s.moodHint}>{mood?'You can move your dot anytime.':'Your dot is private to you.'}</Text><Pressable style={s.heroButton} onPress={onBack}><Text style={s.heroButtonText}>Done ✦</Text></Pressable></>}

function AuthFlow({step,setStep,name,setName,code,setCode}){if(step==='welcome')return <SafeAreaView style={s.safe}><View style={s.onboard}><Text style={s.bigStar}>✦</Text><Text style={s.brand}>fieldbook</Text><Text style={s.welcome}>Your moments{`\n`}belong here.</Text><Text style={s.lede}>A private place for the stuff you notice, try, feel, and make happen at RHI.</Text><Pressable style={s.heroButton} onPress={()=>setStep('why')}><Text style={s.heroButtonText}>Show me around →</Text></Pressable><Text style={s.privacyNote}>You choose what stays yours and what gets shared.</Text><Pressable onPress={()=>setStep('staff')}><Text style={s.staffLink}>I’m staff / a facilitator</Text></Pressable></View></SafeAreaView>;
  if(step==='why')return <SafeAreaView style={s.safe}><View style={s.onboard}><Text style={s.eyebrow}>HOW IT WORKS</Text><Text style={s.h2}>Notice it.{`\n`}Save it.{`\n`}See the bigger picture.</Text><View style={s.bullets}><Text style={s.bullet}>✦ Drop tiny moments — private by default.</Text><Text style={s.bullet}>✦ See what your group is discovering together.</Text><Text style={s.bullet}>✦ Build a power-up card you can keep.</Text></View><Pressable style={s.heroButton} onPress={()=>setStep('join')}><Text style={s.heroButtonText}>Let’s go →</Text></Pressable><Pressable onPress={()=>setStep('welcome')}><Text style={s.back}>← Back</Text></Pressable></View></SafeAreaView>;
  if(step==='staff')return <SafeAreaView style={s.safe}><View style={s.onboard}><Text style={s.eyebrow}>STAFF SPACE</Text><Text style={s.h2}>Welcome back.</Text><Text style={s.lede}>Staff use a separate sign-in so youth notes stay youth-owned.</Text><TextInput placeholder="Work email" autoCapitalize="none" keyboardType="email-address" style={s.authInput}/><TextInput placeholder="Password" secureTextEntry style={s.authInput}/><Pressable style={s.heroButton} onPress={()=>setStep('app')}><Text style={s.heroButtonText}>Sign in</Text></Pressable><Pressable onPress={()=>setStep('welcome')}><Text style={s.back}>← I’m a young person</Text></Pressable></View></SafeAreaView>;
  return <SafeAreaView style={s.safe}><View style={s.onboard}><Text style={s.eyebrow}>MAKE IT YOURS</Text><Text style={s.h2}>What should we{`\n`}call you?</Text><Text style={s.lede}>A nickname is perfect. No real name needed.</Text><TextInput value={name} onChangeText={setName} placeholder="e.g. J, Star, Blue…" style={s.authInput}/><TextInput value={code} onChangeText={setCode} placeholder="Enter your group code" style={s.authInput}/><Pressable style={s.heroButton} onPress={()=>setStep('app')}><Text style={s.heroButtonText}>Enter Fieldbook ✦</Text></Pressable><Text style={s.privacyNote}>Your nickname is only used on this device.</Text></View></SafeAreaView>}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#fffaf2'},splash:{flex:1,backgroundColor:'#3b3744',alignItems:'center',justifyContent:'center'},splashStar:{fontSize:45,color:'#f2bcae'},splashBrand:{fontSize:28,color:'#fff',fontWeight:'700',letterSpacing:2,marginTop:10},splashTag:{fontFamily:'serif',fontSize:17,color:'#d7aaa0',marginTop:8},app:{flex:1,maxWidth:430,alignSelf:'center',width:'100%',backgroundColor:'#fffaf2',padding:24},onboard:{flex:1,padding:28,justifyContent:'center'},brand:{fontWeight:'700',fontSize:15,letterSpacing:1,marginBottom:28,color:'#25232a'},bigStar:{fontSize:44,color:'#ec735f',marginBottom:12},welcome:{fontFamily:'serif',fontSize:44,lineHeight:43,color:'#25232a',marginBottom:16},eyebrow:{fontSize:10,letterSpacing:1.5,color:'#a19a91',marginTop:8},hero:{fontSize:46,lineHeight:45,marginTop:22,color:'#25232a'},h2:{fontFamily:'serif',fontSize:40,lineHeight:39,color:'#25232a',marginTop:16},italic:{fontStyle:'italic',color:'#a65f4e'},lede:{fontSize:15,lineHeight:22,color:'#827d7b',marginTop:15},heroButton:{marginVertical:25,padding:16,borderRadius:15,backgroundColor:'#3b3744',alignItems:'center'},heroButtonText:{color:'#fff',fontWeight:'700',fontSize:15},privacyNote:{fontSize:12,lineHeight:18,color:'#9b9289',textAlign:'center',marginTop:2},staffLink:{color:'#a35e4d',fontSize:12,textAlign:'center',marginTop:40},bullets:{gap:18,marginTop:30},bullet:{fontFamily:'serif',fontSize:18,lineHeight:25,color:'#4b4541'},back:{color:'#9c7569',fontSize:12,marginTop:22},authInput:{height:52,borderColor:'#e9e2d8',borderWidth:1,borderRadius:12,paddingHorizontal:14,marginTop:14,fontSize:15,backgroundColor:'#fffdf9'},section:{fontSize:11,letterSpacing:1.2,color:'#99928a',marginBottom:13},card:{padding:15,borderRadius:12,borderWidth:1,borderColor:'#e9e2d8',backgroundColor:'#fffdf9',marginBottom:9,flexDirection:'row',gap:10},dot:{color:'#ec735f'},cardText:{fontFamily:'serif',fontSize:17},input:{height:150,borderWidth:1,borderColor:'#e9e2d8',borderRadius:12,padding:14,textAlignVertical:'top',marginTop:25,fontFamily:'serif',fontSize:17,backgroundColor:'#fffdf9'},sky:{height:280,borderRadius:18,backgroundColor:'#2d3540',marginTop:25,justifyContent:'center',alignItems:'center'},skyText:{color:'#f5ebe2',fontSize:25,textAlign:'center',lineHeight:35},power:{marginTop:25,borderRadius:16,backgroundColor:'#3b3744',padding:22},quote:{fontFamily:'serif',fontSize:23,lineHeight:29,color:'#f5eee5'},nav:{position:'absolute',bottom:0,left:0,right:0,height:60,flexDirection:'row',justifyContent:'space-around',alignItems:'center',backgroundColor:'#fffaf2'},navText:{fontSize:10,color:'#aaa29a'},activeNav:{fontSize:10,color:'#ec735f',fontWeight:'700'}});
// Compass visual layer styles are appended below the base theme.
s.portraitImage={borderRadius:20};s.portraitHero={height:150,borderRadius:20,overflow:'hidden',marginTop:22,justifyContent:'center',alignItems:'center'};s.portraitStar={fontSize:48,color:'#fff'};s.portraitHeroText={fontFamily:'serif',fontSize:20,color:'#fff',marginTop:7};s.portraitGrid={marginTop:16,gap:8};s.portraitLens={padding:13,borderRadius:12,borderLeftWidth:5,backgroundColor:'#fffdf9',flexDirection:'row',alignItems:'center',gap:10};s.portraitLensDot={fontSize:16};s.portraitLensName={fontFamily:'serif',fontSize:18,color:'#3b3744'};s.portraitLensMeta={fontSize:11,color:'#8b7e79',marginTop:2};s.portraitFooter={fontFamily:'serif',fontSize:16,lineHeight:22,color:'#6f5b59',textAlign:'center',marginTop:18};
s.gardenMood={position:'absolute',right:18,top:14,fontSize:20,color:'#fff'};
s.gardenImage={borderRadius:12};s.gardenWash={position:'absolute',inset:0,backgroundColor:'rgba(45,53,64,0.18)'};
s.fullSkyImage={borderRadius:20};
s.fullSky={height:370,borderRadius:20,backgroundColor:'#2d3540',marginTop:22,position:'relative',overflow:'hidden'};s.fullSkyCompass={position:'absolute',left:'47%',top:'45%',fontSize:38,color:'#f2bcae'};s.fullSkyDot={position:'absolute',fontSize:24,color:'#f2bcae'};s.fullSkyHint={fontFamily:'serif',fontSize:18,color:'#eaded6',textAlign:'center',padding:30,marginTop:145};s.skyReflection={fontFamily:'serif',fontSize:18,lineHeight:24,color:'#6f5b59',textAlign:'center',marginTop:14};
s.skyPreview={marginBottom:16,padding:15,borderRadius:16,backgroundColor:'#2d3540'};s.skyPreviewHeader={flexDirection:'row',justifyContent:'space-between',alignItems:'center'};s.skyPreviewKicker={fontSize:10,letterSpacing:1.2,color:'#f2bcae'};s.skyPreviewMeta={fontSize:10,color:'#d6c8c0'};s.skyField={height:95,marginTop:10,borderRadius:12,backgroundColor:'#35405a',position:'relative',overflow:'hidden',justifyContent:'center',alignItems:'center'};s.skyPreviewDot={position:'absolute',fontSize:22,color:'#f2bcae'};s.skyPreviewHint={fontFamily:'serif',fontSize:15,color:'#e9ded7',textAlign:'center',paddingHorizontal:24};
s.scrollContent={padding:24,paddingBottom:110,backgroundColor:'#fffaf2',minHeight:'100%'};
s.choiceRow={flexDirection:'row',gap:8,marginTop:14};s.choice={flex:1,padding:12,borderRadius:12,backgroundColor:'#fffaf2',alignItems:'center'};s.choiceText={fontSize:12,color:'#a35e4d',fontWeight:'700'};s.lensTap={fontSize:10,color:'#a35e4d',marginTop:9};
s.choiceSelected={backgroundColor:'#ec735f'};s.choiceTextSelected={color:'#fff'};s.saveLens={marginTop:12,padding:13,borderRadius:12,backgroundColor:'#3b3744',alignItems:'center'};s.saveLensDisabled={opacity:0.35};s.saveLensText={color:'#fff',fontWeight:'700',fontSize:13};
s.sliderValue={fontFamily:'serif',fontSize:24,color:'#3b3744',textAlign:'center',marginTop:14};s.sliderTrack={height:8,borderRadius:5,backgroundColor:'#e4d4c7',marginTop:12,position:'relative'};s.sliderFill={height:8,borderRadius:5,backgroundColor:'#ec735f'};s.sliderThumb={position:'absolute',top:-7,width:22,height:22,borderRadius:11,marginLeft:-11,backgroundColor:'#fff',borderWidth:3,borderColor:'#ec735f'};s.sliderLabels={flexDirection:'row',justifyContent:'space-between',marginTop:8};s.sliderLabel={fontSize:10,color:'#8b7e79'};
s.lensTitleLight={fontFamily:'serif',fontSize:19,color:'#fff'};s.lensBodyLight={fontSize:12,lineHeight:17,color:'#fff',opacity:0.9,marginTop:4};s.lensTapLight={fontSize:10,color:'#fff',opacity:0.8,marginTop:10};
s.garden={marginBottom:16,padding:15,borderRadius:16,backgroundColor:'#f1e6df'};s.gardenKicker={fontSize:10,letterSpacing:1.2,color:'#a35e4d'};s.gardenScene={height:110,marginTop:8,borderRadius:12,backgroundColor:'#e4d4c7',position:'relative',overflow:'hidden',alignItems:'center'};s.gardenStem={fontSize:55,lineHeight:28,color:'#4d8b80',marginTop:32};s.gardenLeaf={position:'absolute',fontSize:22,color:'#ec735f'};s.gardenHint={fontFamily:'serif',fontSize:16,color:'#6f5b59',marginTop:43};s.gardenSub={fontSize:11,color:'#8b7e79',marginTop:8};
s.splash={flex:1,backgroundColor:'#fffaf2',alignItems:'center',justifyContent:'center'};s.splashArt={position:'absolute',width:'100%',height:'100%',resizeMode:'cover',opacity:0.92};s.splashBrand={fontSize:34,color:'#2d2940',fontWeight:'700',letterSpacing:3};s.splashTag={fontFamily:'serif',fontSize:18,color:'#8e665d',marginTop:8};
s.moodCard={marginVertical:22,padding:16,borderRadius:15,backgroundColor:'#f1e6df'};s.moodKicker={fontSize:10,letterSpacing:1.2,color:'#a35e4d'};s.moodTitle={fontFamily:'serif',fontSize:20,color:'#3b3744',marginTop:8};s.moodSub={fontSize:11,color:'#8b7e79',marginTop:4};s.signalRow={flexDirection:'row',gap:6,marginBottom:12};s.signalText={fontSize:9,color:'#a35e4d'};s.signal={fontSize:9,color:'#a35e4d',backgroundColor:'#f3ded7',padding:7,borderRadius:14};s.grid={width:280,height:280,borderRadius:18,backgroundColor:'#f3eee6',marginTop:25,position:'relative'};s.gridV={position:'absolute',left:140,top:0,bottom:0,width:1,backgroundColor:'#d9cec3'};s.gridH={position:'absolute',top:140,left:0,right:0,height:1,backgroundColor:'#d9cec3'};s.axisTop={position:'absolute',top:10,left:12,fontSize:10,color:'#9b8f88'};s.axisBottom={position:'absolute',bottom:10,left:12,fontSize:10,color:'#9b8f88'};s.axisLeft={position:'absolute',bottom:10,right:12,fontSize:10,color:'#9b8f88'};s.axisRight={position:'absolute',top:10,right:12,fontSize:10,color:'#9b8f88'};s.gridTap={position:'absolute',width:40,height:40,marginLeft:-20,marginTop:-20,alignItems:'center',justifyContent:'center'};s.gridDot={fontSize:30,color:'#ec735f'};s.moodHint={fontSize:12,color:'#9b9289',textAlign:'center',marginTop:12};s.toast={position:'absolute',bottom:75,left:30,right:30,padding:13,borderRadius:14,backgroundColor:'#3b3744',alignItems:'center'};s.toastText={color:'#fff',fontWeight:'700'};
s.gridShell={width:300,alignSelf:'center',position:'relative',paddingTop:22,paddingBottom:22,marginTop:20};s.gridTopLeft={position:'absolute',top:0,left:4,fontSize:10,color:'#9b8f88'};s.gridTopRight={position:'absolute',top:0,right:4,fontSize:10,color:'#9b8f88'};s.gridBottomLeft={position:'absolute',bottom:0,left:4,fontSize:10,color:'#9b8f88'};s.gridBottomRight={position:'absolute',bottom:0,right:4,fontSize:10,color:'#9b8f88'};s.gridTouch={position:'absolute',inset:0};s.gridDot={position:'absolute',fontSize:30,color:'#ec735f'};

s.lensGrid={gap:8,marginBottom:14};s.lensCard={padding:12,borderRadius:14,backgroundColor:"#f7e7df"};s.lensTitle={fontFamily:"serif",fontSize:18,color:"#3b3744"};s.lensBody={fontSize:12,color:"#8b7e79",marginTop:4};s.lensPrompt={padding:16,borderRadius:14,backgroundColor:"#f7e7df",marginBottom:14};s.lensInput={height:60,borderWidth:1,borderColor:"#e9e2d8",borderRadius:10,padding:10,marginTop:12,backgroundColor:"#fffdf9"};s.lensClose={fontSize:12,color:"#a35e4d",marginTop:10};
